language: python

install:
  - |
    pip install --egg --no-binary pyenv pyenv
    export PATH=~/.pyenv/bin:$PATH
    eval "$(pyenv init -)"
    pyenv install --skip-existing $PYTHON_VERSION
    pyenv global $PYTHON_VERSION
    pyenv shell $PYTHON_VERSION
    pip install -U pip setuptools wheel py
    pip install .

matrix:
  include:
    - os: osx
      language: generic
      env: PYTHON_VERSION=3.6.2
    - os: osx
      language: generic
      env: PYTHON_VERSION=2.7.13

script: python setup.py test
